### ISSUE TITLE
Continue Listening to podcasts

### ISSUE THREAD

**Issue by wotomas** [wotomas/jimmy-life-planner#7]
### PodCast Lists

**An Android Developer Podcast: Fragmented**  
- [x]  001: Welcome & Testing in Android (20160326)
- [x]  002: Android Studio (20160326)
- [x]  003: The RxJava show with Dan Lew (Part 1)
- [x]  004: The RxJava show with Dan Lew (Part 2)
- [x]  005: Image libraries for Android
- [x]  006: Jake Wharton on Becoming a Better Developer and Creating Successful Open Source Projects (Part 1)
- [x]  007: Jake Wharton on Testing, SqlBrite, NotRxAndroid, RxJava and Much More

**Comment by jimmy9gag** [comment]
- [ ] 008: Pocket Casts Amazingness with Philip Simpson
- [ ] 009: Google IO Special
- [ ] 010: Boning Up on Core Java
- [ ] 011: The Fowler Road to a Clean Architecture
- [ ] 012: Continous Integration and Collective Code Ownership
- [ ] 013: Corey Latislaw on TDD and Testing
- [ ] 014: Effective Java for Android developers : Item 1
- [ ] 015: Amanimations – Animations with Amanda
- [ ] 017: Effective Java for Android developers : Item 2
- [ ] 018: Getting Close with Android Nearby
- [ ] 019: 
- [ ] 020: 
- [ ] 021:
